config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#home'

  resources :users, only: [:index, :show]
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts
  resources :activities, only: [:index]

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  include PublicActivity::Model
  
  belongs_to :user
  belongs_to :friend, class_name: "User"

  def accept_friendship
    self.update_attributes(state: "active", friended_at: Time.now)
  end

  def cancel_friendship
    self.destroy
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PublicActivity::Model
  
  belongs_to :user
  validates_presence_of :content
  auto_html_for :content do
    html_escape
    image(:width => 500, :height => 300)
    youtube(:width => 500, :height => 300)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  attr_accessor :login

  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: 'friend_id', dependent: :destroy
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def request_friendship(user_2)
    self.friendships.create(friend: user_2)
  end

  def active_friends
    self.friendships.where(state: "active").map(&:friend) + 
    self.inverse_friendships.where(state: "active").map(&:user)
  end

  def pending_sent_requests
    self.friendships.where(state: "pending")
  end

  def pending_received_requests
    self.inverse_friendships.where(state: "pending")
  end

  def friendship_status(user)
    friendship = Friendship.where(user: [self.id, user.id], friend: [self.id, user.id])
    unless friendship.any?
      return "Not Friends"
    else 
      if friendship.first.state == "active"
        return "Friends"
      elsif friendship.first.user == self
        return "Requested"
      else 
        return "Pending"
      end
    end
  end

  def find_friendship_with(user)
    Friendship.where(user: [self.id, user.id], friend: [self.id, user.id]).first
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @users = current_user.active_friends
    @users.push(current_user)
    @activities = PublicActivity::Activity.where(owner: @users).order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache,:age, :gender, :bio) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache, :age, :gender, :bio)}
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  before_action :find_user, only: [:create, :update, :destroy]
  before_action :find_friendship, only: [:update, :destroy]

  def create
    current_user.request_friendship(@user)
    flash.notice = "Friend Request sent to #{@user.username}"
    redirect_to users_path
  end

  def destroy
    @friendship.destroy
    unless params[:cancel_request]
      flash.notice = "You are no longer friends with #{@user.username}"
    else
      flash.notice = "Request to #{@user.username} cancelled"
    end
    redirect_to users_path
  end

  def update
    @friendship.accept_friendship
    @friendship.create_activity key: "friendship.accepted", owner: @friendship.user, recipient: @friendship.friend
    @friendship.create_activity key: "friendship.accepted", owner: @friendship.friend, recipient: @friendship.user
    flash.notice = "You are now friends with #{@user.username}"
    redirect_to users_path

  end

  private
  def find_user
    @user = User.find(params[:user_id])
  end

  def find_friendship
    @friendship = Friendship.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :destroy]

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      @post.create_activity key: "post.created", owner: @post.user
      flash.notice = "Post created"
    else
      flash.notice = "Something went wrong"
    end
    redirect_to user_path(@post.user.username)
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to user_path(@post.user.username)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash.notice = "Post deleted"
    redirect_to(:back)
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]
  before_action :get_counts, only: [:index]

  def index
    case params[:show] 
    when "friends"
      @users = current_user.active_friends
    when "requested"
      @users = current_user.pending_sent_requests.map(&:friend)
    when "pending"
      @users = current_user.pending_received_requests.map(&:user)
    else
      @users = User.where.not(id: current_user.id)
    end
  end

  def show
    @post = Post.new
    @posts = @user.posts.order("created_at DESC")
    @activities = PublicActivity::Activity.where(owner: @user).order('created_at DESC')
  end

  private

  def find_user
    @user = User.find_by(username: params[:id])
  end

  def get_counts
    @friends_count = current_user.active_friends.size
    @pending_sent_requests_count = current_user.pending_sent_requests.map(&:friend).size
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pending_received_requests_count
    current_user.pending_received_requests.map(&:user).size
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def friendship_status_button(user)
    case current_user.friendship_status(user)
      when "Not Friends"
        link_to "Add as Friend", friendships_path(user_id: user.id), method: :post, class: "btn btn-sm btn-success"
      when "Friends"
        link_to "Remove as Friend", friendship_path(id: current_user.find_friendship_with(user).id, user_id: user.id), method: :delete, class: "btn btn-sm btn-success"
      when "Requested"
        link_to "Cancel Request", friendship_path(id: current_user.find_friendship_with(user).id, user_id: user.id, cancel_request: true), method: :delete, class: "btn btn-sm btn-success"
      when "Pending"
        link_to "Accept Request", friendship_path(id: current_user.find_friendship_with(user).id, user_id: user.id), method: :put, class: "btn btn-sm btn-success"
    end
  end
end

app/views/activities/index.html.erb
<div class="container">
  <ul class="timeline">
    <% @activities.each_with_index do |activity, index| %>
    <% unless activity.trackable_type == "Friendship" && activity.owner == current_user %>
    <% if (index%2 == 0) %>
    <li class="timeline-inverted">
      <% else %>
      <li>
        <% end %>
        <% if activity.trackable %>
        <div class="timeline-badge">
          <%= image_tag activity.owner.avatar.url(:thumb), class: "img-responsive img-circle" %>
        </div>
        <div class="timeline-panel">
          <div class="timeline-heading">
            <h4 class="timeline-title"><%= link_to activity.owner.username, user_path(activity.owner.username) %></h4>
            <small><%= time_ago_in_words(activity.created_at) %> ago</small>
          </div>
          <div class="timeline-body">
            <% if activity.trackable_type == "Post" %>
            <%= raw(activity.trackable.content_html) %>
            <% else %>
            <p><%= link_to activity.owner.username, user_path(activity.owner.username) %> is now friends with <%= link_to activity.recipient.username, user_path(activity.recipient.username) %></p>
            <% end %>
          </div>
        </div>
        <% end %>
        
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>

app/views/common/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Social Network", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(activities_path) %>"><%= link_to "Timeline", activities_path %></li>
        <li class="<%= 'active' if current_page?(users_path) %>">
          <%= link_to users_path do %>
            <span>People<span class="badge"><%= pending_received_requests_count if pending_received_requests_count > 0 %></span></span>
          <% end %>
        </li>
        <li class="dropdown">
          <%= link_to('#', class: "dropdown-toggle", data: {toggle: "dropdown"}) do %>
          <%= image_tag current_user.avatar.url(:thumb), class: "img-circle nav-profile-pic" %>
          <%= current_user.username %>
          <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to "Profile", user_path(current_user.username) %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li class="<%= 'active' if current_page?(new_user_registration_path) %>"><%= link_to "Sign Up", new_user_registration_path %></li>
        <li class="<%= 'active' if current_page?(new_user_session_path) %>"><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialNetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'common/header' %>
<% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
    <button class="close" data-dismiss = "alert">x</button>
    <%= message %>
  </div>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="thumbail">
  <% if current_user %>
    
  <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :content, label: false, placeholder: "You can also post image/video by pasting the URL here.", required: true %>
  <%= f.button :submit, "Post", class: "btn submit-btn" %>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to user_path(post.user.username) do %>
    <%= image_tag post.user.avatar.url(:thumb) %> <%= post.user.username %>
    <% end %> posted this about <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user == post.user %>
    <%= link_to post_path(post), method: :delete, data: {confirm: "Are you sure you want to delete this?"} do %>
    <%= fa_icon "times", class: "pull-right delete-post" %>
    <% end %>
    <%= link_to edit_post_path(post) do %>
    <%= fa_icon "pencil", class: "pull-right edit-post" %>
    <% end %>
    <% end %>
  </div>
  <div class="panel-body post-content">
    <%= raw(post.content_html) %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="col-md-offset-3 col-md-6">
  <div class="panel panel-success">
    <div class="panel-heading text-center"><strong>What's on your mind?</strong></div>
    <div class="panel-body">
      <%= render 'posts/form' %>
    </div>
  </div>
</div>

app/views/public_activity/friendship/_accepted.html.erb
<% if activity.trackable %>
  <p><%= link_to activity.owner.username, user_path(activity.owner.username) %> is now friends with <%= link_to activity.recipient.username, user_path(activity.recipient.username) %></p>
<% end %>

app/views/public_activity/post/_created.html.erb
<% if activity.trackable %>
<p><%= link_to activity.owner.username, user_path(activity.owner.username) %> posted something <%= time_ago_in_words(activity.created_at) %> ago.</p>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-3">
  <div class="thumbnail">
    <%= link_to user_path(user.username) do %>
    <%= image_tag user.avatar.url, class: "img-responsive show-user-pic" %>
    <% end %>
    <div class="caption text-center">
      <h3><%= user.username %></h3>
      <%= friendship_status_button(user) if current_user %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron text-center">
  <h2>People</h2>
  <div class="btn-group" role="group">
    <%=link_to "Everyone", users_path, class: "btn btn-default #{'active' unless params[:show]}" %>
    <%=link_to "Friends (#{@friends_count})", users_path(show: "friends"), class: "btn btn-default #{'active' if params[:show] == 'friends'}" %>
    <%=link_to "Requested (#{@pending_sent_requests_count})", users_path(show: "requested"), class: "btn btn-default #{'active' if params[:show] == 'requested'}" %> 
    <%=link_to "Pending (#{pending_received_requests_count})", users_path(show: "pending"), class: "btn btn-default #{'active' if params[:show] == 'pending'}" %>
  </div>
</div>

<div class="container users-index">
  <div class="row">
    <%= render @users %>
  </div>
</div>

app/views/users/show.html.erb
<!-- <div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @user.avatar.url(:profile_page) %>
      </div>
      <div class="col-md-4">
        <h2><%= @user.username %></h2>
        <h3>Age: <%= @user.age %></h3> 
        <h3>Gender: <%= @user.gender %></h3>
      </div>
      <div class="col-md-4">
        <h2>About Me</h2>
        <p><%= @user.bio %></p>
      </div>
    </div>
  </div>
</div> -->

<div class="custom-container">
  <div class="row">
    <div class="col-md-2">
      <div class="thumbnail">
        <%= image_tag @user.avatar.url(:profile_page) %>
        <div class="caption">
          <h3 class="text-center"><%= @user.username %></h3>
          <div class="row">
            <div class="col-md-6">
              <p class="text-center"><strong>Age: </strong></p>
              <p class="text-center"><strong>Gender: </strong></p>
              <p class="text-center"><strong>Bio: </strong></p>
            </div>
            <div class="col-md-6">
              <p><%= @user.age %></p>
              <p><%= @user.gender %></p>
            </div>
            <div class="row">
              <p><%= @user.bio %></p>
            </div>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading text-center"><strong>Friends (<%= @user.active_friends.size %>)</strong></div>
        <div class="panel-body">
          <% (@user.active_friends).each do |friend| %>
          <%= link_to user_path(friend.username) do %>
          <%= image_tag friend.avatar.url, class: "show-friends-pic" %>
          <% end %>
          <% end %>
        </div>
      </div>

    </div>

    <div class="col-md-6">
      <% if current_user == @user %>
      <div class="panel panel-success">
        <div class="panel-heading text-center"><strong>What's on your mind?</strong></div>
        <div class="panel-body">
          <%= render 'posts/form' %>
        </div>
      </div>
      <% end %>
      <%= render @posts %>
    </div>
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading text-center"><strong>Activity</strong></div>
        <div class="panel-body">
          <%= render_activities(@activities) %>
        </div>
      </div>
    </div>
  </div>
</div>